// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chunks.sql

package db

import (
	"context"
)

const deleteChunk = `-- name: DeleteChunk :exec
DELETE FROM code_chunks
WHERE id = ?
`

func (q *Queries) DeleteChunk(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteChunkStmt, deleteChunk, id)
	return err
}

const getChunkBySHA = `-- name: GetChunkBySHA :one
SELECT
    id,
    file_path,
    symbol,
    sha,
    lang,
    chunk_type,
    embedding,
    embedding_provider,
    embedding_dimensions,
    pampa_tags,
    pampa_intent,
    pampa_description,
    doc_comments,
    variables_used,
    context_info,
    created_at,
    updated_at
FROM code_chunks
WHERE sha = ?
LIMIT 1
`

func (q *Queries) GetChunkBySHA(ctx context.Context, sha string) (CodeChunk, error) {
	row := q.queryRow(ctx, q.getChunkBySHAStmt, getChunkBySHA, sha)
	var i CodeChunk
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Symbol,
		&i.Sha,
		&i.Lang,
		&i.ChunkType,
		&i.Embedding,
		&i.EmbeddingProvider,
		&i.EmbeddingDimensions,
		&i.PampaTags,
		&i.PampaIntent,
		&i.PampaDescription,
		&i.DocComments,
		&i.VariablesUsed,
		&i.ContextInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChunksByFilePath = `-- name: GetChunksByFilePath :many
SELECT
    id,
    file_path,
    symbol,
    sha,
    lang,
    chunk_type,
    embedding,
    embedding_provider,
    embedding_dimensions,
    pampa_tags,
    pampa_intent,
    pampa_description,
    doc_comments,
    variables_used,
    context_info,
    created_at,
    updated_at
FROM code_chunks
WHERE file_path = ?
ORDER BY id
`

func (q *Queries) GetChunksByFilePath(ctx context.Context, filePath string) ([]CodeChunk, error) {
	rows, err := q.query(ctx, q.getChunksByFilePathStmt, getChunksByFilePath, filePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodeChunk{}
	for rows.Next() {
		var i CodeChunk
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Symbol,
			&i.Sha,
			&i.Lang,
			&i.ChunkType,
			&i.Embedding,
			&i.EmbeddingProvider,
			&i.EmbeddingDimensions,
			&i.PampaTags,
			&i.PampaIntent,
			&i.PampaDescription,
			&i.DocComments,
			&i.VariablesUsed,
			&i.ContextInfo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChunksByProvider = `-- name: GetChunksByProvider :many
SELECT
    id,
    file_path,
    symbol,
    sha,
    lang,
    chunk_type,
    embedding,
    embedding_provider,
    embedding_dimensions,
    pampa_tags,
    pampa_intent,
    pampa_description,
    doc_comments,
    variables_used,
    context_info,
    created_at,
    updated_at
FROM code_chunks
WHERE embedding_provider = ?
ORDER BY id
`

func (q *Queries) GetChunksByProvider(ctx context.Context, embeddingProvider *string) ([]CodeChunk, error) {
	rows, err := q.query(ctx, q.getChunksByProviderStmt, getChunksByProvider, embeddingProvider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodeChunk{}
	for rows.Next() {
		var i CodeChunk
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Symbol,
			&i.Sha,
			&i.Lang,
			&i.ChunkType,
			&i.Embedding,
			&i.EmbeddingProvider,
			&i.EmbeddingDimensions,
			&i.PampaTags,
			&i.PampaIntent,
			&i.PampaDescription,
			&i.DocComments,
			&i.VariablesUsed,
			&i.ContextInfo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChunk = `-- name: InsertChunk :exec
INSERT INTO code_chunks (
    id,
    file_path,
    symbol,
    sha,
    lang,
    chunk_type,
    embedding,
    embedding_provider,
    embedding_dimensions,
    pampa_tags,
    pampa_intent,
    pampa_description,
    doc_comments,
    variables_used,
    context_info
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertChunkParams struct {
	ID                  string  `json:"id"`
	FilePath            string  `json:"file_path"`
	Symbol              string  `json:"symbol"`
	Sha                 string  `json:"sha"`
	Lang                string  `json:"lang"`
	ChunkType           *string `json:"chunk_type"`
	Embedding           []byte  `json:"embedding"`
	EmbeddingProvider   *string `json:"embedding_provider"`
	EmbeddingDimensions *int64  `json:"embedding_dimensions"`
	PampaTags           *string `json:"pampa_tags"`
	PampaIntent         *string `json:"pampa_intent"`
	PampaDescription    *string `json:"pampa_description"`
	DocComments         *string `json:"doc_comments"`
	VariablesUsed       *string `json:"variables_used"`
	ContextInfo         *string `json:"context_info"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.exec(ctx, q.insertChunkStmt, insertChunk,
		arg.ID,
		arg.FilePath,
		arg.Symbol,
		arg.Sha,
		arg.Lang,
		arg.ChunkType,
		arg.Embedding,
		arg.EmbeddingProvider,
		arg.EmbeddingDimensions,
		arg.PampaTags,
		arg.PampaIntent,
		arg.PampaDescription,
		arg.DocComments,
		arg.VariablesUsed,
		arg.ContextInfo,
	)
	return err
}
