// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteChunkStmt, err = db.PrepareContext(ctx, deleteChunk); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteChunk: %w", err)
	}
	if q.getChunkBySHAStmt, err = db.PrepareContext(ctx, getChunkBySHA); err != nil {
		return nil, fmt.Errorf("error preparing query GetChunkBySHA: %w", err)
	}
	if q.getChunksByFilePathStmt, err = db.PrepareContext(ctx, getChunksByFilePath); err != nil {
		return nil, fmt.Errorf("error preparing query GetChunksByFilePath: %w", err)
	}
	if q.getChunksByProviderStmt, err = db.PrepareContext(ctx, getChunksByProvider); err != nil {
		return nil, fmt.Errorf("error preparing query GetChunksByProvider: %w", err)
	}
	if q.getIntentionsByQueryStmt, err = db.PrepareContext(ctx, getIntentionsByQuery); err != nil {
		return nil, fmt.Errorf("error preparing query GetIntentionsByQuery: %w", err)
	}
	if q.getQueryPatternByPatternStmt, err = db.PrepareContext(ctx, getQueryPatternByPattern); err != nil {
		return nil, fmt.Errorf("error preparing query GetQueryPatternByPattern: %w", err)
	}
	if q.insertChunkStmt, err = db.PrepareContext(ctx, insertChunk); err != nil {
		return nil, fmt.Errorf("error preparing query InsertChunk: %w", err)
	}
	if q.insertIntentionStmt, err = db.PrepareContext(ctx, insertIntention); err != nil {
		return nil, fmt.Errorf("error preparing query InsertIntention: %w", err)
	}
	if q.insertQueryPatternStmt, err = db.PrepareContext(ctx, insertQueryPattern); err != nil {
		return nil, fmt.Errorf("error preparing query InsertQueryPattern: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteChunkStmt != nil {
		if cerr := q.deleteChunkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteChunkStmt: %w", cerr)
		}
	}
	if q.getChunkBySHAStmt != nil {
		if cerr := q.getChunkBySHAStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChunkBySHAStmt: %w", cerr)
		}
	}
	if q.getChunksByFilePathStmt != nil {
		if cerr := q.getChunksByFilePathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChunksByFilePathStmt: %w", cerr)
		}
	}
	if q.getChunksByProviderStmt != nil {
		if cerr := q.getChunksByProviderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChunksByProviderStmt: %w", cerr)
		}
	}
	if q.getIntentionsByQueryStmt != nil {
		if cerr := q.getIntentionsByQueryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIntentionsByQueryStmt: %w", cerr)
		}
	}
	if q.getQueryPatternByPatternStmt != nil {
		if cerr := q.getQueryPatternByPatternStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getQueryPatternByPatternStmt: %w", cerr)
		}
	}
	if q.insertChunkStmt != nil {
		if cerr := q.insertChunkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertChunkStmt: %w", cerr)
		}
	}
	if q.insertIntentionStmt != nil {
		if cerr := q.insertIntentionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertIntentionStmt: %w", cerr)
		}
	}
	if q.insertQueryPatternStmt != nil {
		if cerr := q.insertQueryPatternStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertQueryPatternStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	deleteChunkStmt              *sql.Stmt
	getChunkBySHAStmt            *sql.Stmt
	getChunksByFilePathStmt      *sql.Stmt
	getChunksByProviderStmt      *sql.Stmt
	getIntentionsByQueryStmt     *sql.Stmt
	getQueryPatternByPatternStmt *sql.Stmt
	insertChunkStmt              *sql.Stmt
	insertIntentionStmt          *sql.Stmt
	insertQueryPatternStmt       *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		deleteChunkStmt:              q.deleteChunkStmt,
		getChunkBySHAStmt:            q.getChunkBySHAStmt,
		getChunksByFilePathStmt:      q.getChunksByFilePathStmt,
		getChunksByProviderStmt:      q.getChunksByProviderStmt,
		getIntentionsByQueryStmt:     q.getIntentionsByQueryStmt,
		getQueryPatternByPatternStmt: q.getQueryPatternByPatternStmt,
		insertChunkStmt:              q.insertChunkStmt,
		insertIntentionStmt:          q.insertIntentionStmt,
		insertQueryPatternStmt:       q.insertQueryPatternStmt,
	}
}
