// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type CodeChunk struct {
	ID                  string     `json:"id"`
	FilePath            string     `json:"file_path"`
	Symbol              string     `json:"symbol"`
	Sha                 string     `json:"sha"`
	Lang                string     `json:"lang"`
	ChunkType           *string    `json:"chunk_type"`
	Embedding           []byte     `json:"embedding"`
	EmbeddingProvider   *string    `json:"embedding_provider"`
	EmbeddingDimensions *int64     `json:"embedding_dimensions"`
	PampaTags           *string    `json:"pampa_tags"`
	PampaIntent         *string    `json:"pampa_intent"`
	PampaDescription    *string    `json:"pampa_description"`
	DocComments         *string    `json:"doc_comments"`
	VariablesUsed       *string    `json:"variables_used"`
	ContextInfo         *string    `json:"context_info"`
	CreatedAt           *time.Time `json:"created_at"`
	UpdatedAt           *time.Time `json:"updated_at"`
}

type IntentionCache struct {
	ID              int64      `json:"id"`
	QueryNormalized string     `json:"query_normalized"`
	OriginalQuery   string     `json:"original_query"`
	TargetSha       string     `json:"target_sha"`
	Confidence      *float64   `json:"confidence"`
	UsageCount      *int64     `json:"usage_count"`
	CreatedAt       *time.Time `json:"created_at"`
	LastUsed        *time.Time `json:"last_used"`
}

type QueryPattern struct {
	ID             int64      `json:"id"`
	Pattern        string     `json:"pattern"`
	Frequency      *int64     `json:"frequency"`
	TypicalResults *string    `json:"typical_results"`
	CreatedAt      *time.Time `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
}
