// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_patterns.sql

package db

import (
	"context"
)

const getQueryPatternByPattern = `-- name: GetQueryPatternByPattern :one
SELECT
    id,
    pattern,
    frequency,
    typical_results,
    created_at,
    updated_at
FROM query_patterns
WHERE pattern = ?
LIMIT 1
`

func (q *Queries) GetQueryPatternByPattern(ctx context.Context, pattern string) (QueryPattern, error) {
	row := q.queryRow(ctx, q.getQueryPatternByPatternStmt, getQueryPatternByPattern, pattern)
	var i QueryPattern
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.Frequency,
		&i.TypicalResults,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertQueryPattern = `-- name: InsertQueryPattern :exec
INSERT INTO query_patterns (
    pattern,
    frequency,
    typical_results
) VALUES (?, ?, ?)
ON CONFLICT(pattern) DO UPDATE SET
    frequency = excluded.frequency,
    typical_results = excluded.typical_results,
    updated_at = CURRENT_TIMESTAMP
`

type InsertQueryPatternParams struct {
	Pattern        string  `json:"pattern"`
	Frequency      *int64  `json:"frequency"`
	TypicalResults *string `json:"typical_results"`
}

func (q *Queries) InsertQueryPattern(ctx context.Context, arg InsertQueryPatternParams) error {
	_, err := q.exec(ctx, q.insertQueryPatternStmt, insertQueryPattern, arg.Pattern, arg.Frequency, arg.TypicalResults)
	return err
}
