// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	DeleteChunk(ctx context.Context, id string) error
	GetChunkBySHA(ctx context.Context, sha string) (CodeChunk, error)
	GetChunksByFilePath(ctx context.Context, filePath string) ([]CodeChunk, error)
	GetChunksByProvider(ctx context.Context, embeddingProvider *string) ([]CodeChunk, error)
	GetIntentionsByQuery(ctx context.Context, queryNormalized string) ([]IntentionCache, error)
	GetQueryPatternByPattern(ctx context.Context, pattern string) (QueryPattern, error)
	InsertChunk(ctx context.Context, arg InsertChunkParams) error
	InsertIntention(ctx context.Context, arg InsertIntentionParams) error
	InsertQueryPattern(ctx context.Context, arg InsertQueryPatternParams) error
}

var _ Querier = (*Queries)(nil)
